In [17]:
import pandas as pd
# function to split datasets# 
from sklearn.model_selection import train_test_split
import numpy as np
# Trying to use neural network for modeling#
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.neural_network import MLPClassifier
class Model_LR: 
    def __init__(self, datafile = "/Users/yangb8/gRNA_feature_binary_continuous.xlsx"):
        self.df = pd.read_excel(datafile)
        self.linear_regression = LinearRegression(fit_intercept=True)
    # split module to shuffle and split data for traning and testin purposes##
    def split(self, test_size):
        X = np.array(self.df.iloc[:,2:])
    #label for the editing efficiency score on a scale from 0 to 10# 
        y = np.array(self.df.iloc[:,0])
        print (X)
        print (y)
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size = test_size, random_state = 42)
    def fit(self):
        self.model = self.linear_regression.fit(self.X_train, self.y_train,)
    def predict(self):
        result = self.linear_regression.predict(self.X_test)
        return result
if __name__ == '__main__':
    model_instance = Model_LR()
    model_instance.split(0.25)
    model_instance.fit() 
    print(model_instance.predict())   
    print("LR_score: ",     model_instance.model.score(model_instance.X_test, model_instance.y_test))
## SVC##
class Model_SVR: 
    def __init__(self, datafile = "/Users/yangb8/gRNA_feature_binary_continuous.xlsx"):
        self.df = pd.read_excel(datafile)
        self.SVR = SVR(C=0.3,gamma = "scale")
    # split module to shuffle and split data for traning and testin purposes##
    def split(self, test_size):
        X = np.array(self.df.iloc[:,2:])
    #label for the editing efficiency score on a scale from 0 to 10# 
        y = np.array(self.df.iloc[:,0])
        print (X)
        print (y)
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size = test_size, random_state = 42)
    def fit(self):
        self.model = self.SVR.fit(self.X_train, self.y_train,)
    def predict(self):
        result = self.SVR.predict(self.X_test)
        return result
if __name__ == '__main__':
    model_instance = Model_SVR()
    model_instance.split(0.25)
    model_instance.fit() 
    print(model_instance.predict())   
    print("SVR_score: ",     model_instance.model.score(model_instance.X_test, model_instance.y_test))
##Neural network_MLPC##   
class Model_MLPC:
    def __init__(self, datafile = "/Users/yangb8/gRNA_feature_binary_binned.xlsx"):
        self.df = pd.read_excel(datafile)
        self.logistic_regression = LogisticRegression()
        self.MLPC = MLPClassifier()
        self.svc = SVC()
    # split module to shuffle and split data for traning and testin purposes##
    def split(self, test_size):
        X = np.array(self.df.iloc[:,2:])
    #label for the editing efficiency score on a scale from 0 to 10# 
        y = np.array(self.df.iloc[:,0])
        y = y.astype("int")
        print (X)
        print (y)
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size = test_size, random_state = 42)
    def fit(self):
        self.model = self.MLPC.fit(self.X_train, self.y_train,)
    def predict(self):
        result = self.MLPC.predict(self.X_test)
        return result
if __name__ == '__main__':
    model_instance = Model_MLPC()
    model_instance.split(0.25)
    model_instance.fit() 
    print(model_instance.predict())   
    print("MLPC_Accuracy: ",     model_instance.model.score(model_instance.X_test, model_instance.y_test))
        
        
        

[[1 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 1 0]
 [0 0 1 ... 0 1 0]
 [0 1 0 ... 0 1 0]]
[ 3.975  1.875  5.125 20.9   12.3   15.125  5.65   4.5    3.35   4.35
  7.7    2.85  33.325 41.725  1.175  0.725  2.55  27.525 21.725 35.325
  5.6   27.975 14.075 16.275 33.7    5.675  7.925  8.625 68.275 27.3
  6.825 40.475 29.8   12.575  2.1   24.925 17.45  29.125 32.525 10.275
 28.325 40.975 44.5    6.225  3.55  73.95  10.45  11.35  73.825 25.8
 12.2   23.1   48.175  7.8    2.775  5.1    5.275 21.55   3.85   7.575
 19.6   18.775 51.725 47.175  2.1    9.225  7.225  7.225  4.2    4.55
 10.425 98.575  0.     0.     0.     0.     0.     0.     0.     0.
  0.     0.   ]
[ 227.85810733   21.37044508  -97.58051448  -69.79626715   86.71521697
 -185.45943042   11.14650376  167.19947513  153.4174021  -144.72000162
  209.21875034  -56.80346291  -17.07199196  -29.28599205 -204.33810842
  197.53379323  -57.70339248  -66.52568379  -54.2352674   -58.69633491
 -413.76468479]
LR_sc

/Users/yangb8/miniconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
