In [2]:
import pandas as pd
# function to split datasets# 
from sklearn.model_selection import train_test_split
import numpy as np
## a few regression methods including LinearRegression and SVM regression##
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
## a neural network model##
from sklearn.neural_network import MLPClassifier

##Linear_regression module##
class Model_LR: 
    def __init__(self, datafile = "gRNA_feature_binary_continuous.xlsx"):
        self.df = pd.read_excel(datafile)
        self.linear_regression = LinearRegression(fit_intercept=True)
    def fit(self):
        self.X = np.array(self.df.iloc[:,2:])
        self.y = np.array(self.df.iloc[:,0])
        self.model = self.linear_regression.fit(self.X, self.y)
if __name__ == '__main__':
    model_instance = Model_LR()
    model_instance.fit()    
    print("LR_score: ", model_instance.model.score(model_instance.X, model_instance.y)

## SVR module##
class Model_SVR: 
    def __init__(self, datafile = "gRNA_feature_binary_continuous.xlsx"):
        self.df = pd.read_excel(datafile)
        self.SVR = SVR(C=0.3,gamma = "scale")
    def fit(self):
        self.X = np.array(self.df.iloc[:,2:])
        self.y = np.array(self.df.iloc[:,0])
        self.model = self.SVR.fit(self.X, self.y)
if __name__ == '__main__':
    model_instance = Model_SVR()
    model_instance.fit()   
    print("SVR_score: ",model_instance.model.score(model_instance.X, model_instance.y))
    
##Neural network_MLPC##   
class Model_MLPC:
    def __init__(self, datafile = "gRNA_feature_binary_binned.xlsx"):
        self.df = pd.read_excel(datafile)
        self.MLPC = MLPClassifier()
        self.svc = SVC()
    # split module to shuffle and split data for traning and testin purposes##
    def split(self, test_size):
        X = np.array(self.df.iloc[:,2:])
    #label for the editing efficiency score on a scale from 0 to 10# 
        y = np.array(self.df.iloc[:,0])
        y = y.astype("int")
    #shuffle and randomized data for training and test##
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size = test_size, random_state = 42)
    def fit(self):
        self.model = self.MLPC.fit(self.X_train, self.y_train,)
    def predict(self):
        result = self.MLPC.predict(self.X_test)
        return result
if __name__ == '__main__':
    model_instance = Model_MLPC()
    model_instance.split(0.25)
    model_instance.fit() 
    print(model_instance.predict())   
    print("MLPC_Accuracy: ",model_instance.model.score(model_instance.X_test, model_instance.y_test))
        
        
        

LR_score:  0.6709621447099378
SVR_score:  -0.15466851234835377
[[1 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 1 0]
 [0 0 1 ... 0 1 0]
 [0 1 0 ... 0 1 0]]
[ 1  1  3  2  2  1  1  1  1  1  4  5  1  1  1  1  3  3  4  1  3  2  2  4
  1  1  1  7  3  5  3  2  1  3  2  3  4  2  3  5  5  1  1  8  2  2  8  3
  2  3  5  1  1  1  1  3  1  1  1  2  2  6  5  1  1  1  1  1  1  2 10  0
  0  0  0  0  0  0  0  0  0  0]
[3 1 1 1 1 3 1 1 3 1 1 1 1 1 2 1 1 2 1 1 1]
MLPC_Accuracy:  0.42857142857142855


/Users/yangb8/miniconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
