In [2]:
import pandas as pd
# function to split datasets# 
from sklearn.model_selection import train_test_split
import numpy as np
# Trying to use neural network for modeling#
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.neural_network import MLPClassifier
class Model:
  def __init__(self, datafile = "/Users/yangb8/gRNA_feature_binary_int.xlsx"):
    self.df = pd.read_excel(datafile)
    self.logistic_regression = LogisticRegression()
    self.MLPC = MLPClassifier()
    self.svc = SVC()
    # split module to shuffle and split data for traning and testin purposes##
  def split(self, test_size):
    X = np.array(self.df.iloc[:,2:])
    #label for the editing efficiency score on a scale from 0 to 10# 
    y = np.array(self.df.iloc[:,0])
    y = y.astype("int")
    print (X)
    print (y)
    self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size = test_size, random_state = 42)
  def fit(self):
    self.model = self.MLPC.fit(self.X_train, self.y_train,)
  def predict(self):
    result = self.MLPC.predict(self.X_test)
    return result
if __name__ == '__main__':
    model_instance = Model()
    model_instance.split(0.25)
    model_instance.fit() 
    print(model_instance.predict())   
    print("Accuracy: ",     model_instance.model.score(model_instance.X_test, model_instance.y_test))
        
        
        

[[1 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 1 0]
 [0 0 1 ... 0 1 0]
 [0 1 0 ... 0 1 0]]
[ 1  1  3  2  2  1  1  1  1  1  4  5  1  1  1  1  3  3  4  1  3  2  2  4
  1  1  1  7  3  5  3  2  1  3  2  3  4  2  3  5  5  1  1  8  2  2  8  3
  2  3  5  1  1  1  1  3  1  1  1  2  2  6  5  1  1  1  1  1  1  2 10  0
  0  0  0  0  0  0  0  0  0  0]
[3 1 1 1 1 3 1 1 3 1 1 1 1 1 2 1 1 2 1 3 1]
Accuracy:  0.42857142857142855


/Users/yangb8/miniconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
